[[override]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[override]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"


[[override]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/didip/tollbooth"
  version = "4.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/didip/tollbooth_chi"
