# Taskfile used with https://github.com/go-task/task/
build:
  desc: Builds the server and generates a binary for the current OS
  cmds:
    - go build .

run:
  desc: Builds and runs the server locally
  deps: [build]
  sources: 
    - ./*.go
  cmds:
    - ./simple-charity-server

vendor:
  desc: Updates the vendor directory
  cmds:
    - dep ensure

test:
  desc: Runs go test on the server
  cmds:
    - go test

cover:
  desc: Runs coverage on the server
  cmds:
    - go test -coverprofile=coverage.out && go tool cover -html=coverage.out

docs:
  desc: Runs a godoc server locally
  cmds:
    - godoc -http=":6060"


docker-build:
  desc: Builds and tags the docker image
  cmds: 
    - docker build -t kvss/simple-charity-server .

docker-run:
  desc: Runs the latest built docker image
  deps: ["docker-build"]
  cmds:
    - docker run kvss/simple-charity-server